# -*- coding: utf-8 -*-
"""Project_I_GenAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g_DLtHY64SxdRBCcQbvnCxRmMO6LeADT

<center><font size=8>Stock_Analysis</center></font>

<center><p float="center">
  <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEtr22UkeoMZnFCftID0sh5ZO-uCM7wKXp5dLpcf2CRsa_x_gvQ80wQEA8&s=10" width="720"/>
</p></center>

## **Problem Statement**

### Business Context

The prices of the stocks of companies listed under a global exchange are influenced by a variety of factors, with the company's financial performance, innovations and collaborations, and market sentiment being factors that play a significant role. News and media reports can rapidly affect investor perceptions and, consequently, stock prices in the highly competitive financial industry. With the sheer volume of news and opinions from a wide variety of sources, investors and financial analysts often struggle to stay updated and accurately interpret its impact on the market. As a result, investment firms need sophisticated tools to analyze market sentiment and integrate this information into their investment strategies.

### Problem Definition

With an ever-rising number of news articles and opinions, an investment startup aims to leverage artificial intelligence to address the challenge of interpreting stock-related news and its impact on stock prices. They have collected historical daily news for a specific company listed under NASDAQ, along with data on its daily stock price and trade volumes.

As a member of the Data Science and AI team in the startup, you have been tasked with developing an AI-driven sentiment analysis system that will automatically process and analyze news articles to gauge market sentiment, and summarizing the news at a weekly level to enhance the accuracy of their stock price predictions and optimize investment strategies. This will empower their financial analysts with actionable insights, leading to more informed investment decisions and improved client outcomes.

### Data Dictionary

* `Date` : The date the news was released
* `News` : The content of news articles that could potentially affect the company's stock price
* `Open` : The stock price (in \$) at the beginning of the day
* `High` : The highest stock price (in \$) reached during the day
* `Low` :  The lowest stock price (in \$) reached during the day
* `Close` : The adjusted stock price (in \$) at the end of the day
* `Volume` : The number of shares traded during the day
* `Label` : The sentiment polarity of the news content
    * 1: positive
    * 0: neutral
    * -1: negative

## **Installing and Importing the necessary libraries**
"""

# installing the sentence-transformers and gensim libraries for word embeddings
!pip install numpy==1.26.4 \
             scikit-learn==1.4.2 \
             scipy==1.13.1 \
             gensim==4.3.3 \
             sentence-transformers==3.4.1 \
             pandas==2.2.2

# to read and manipulate the data
import numpy as np
import pandas as pd
pd.set_option('max_colwidth', None)    # setting column to the maximum column width as per the data

# to visualise data
import matplotlib.pyplot as plt
import seaborn as sns

# To import Word2Vec
from gensim.models import Word2Vec

# Deep Learning library
import torch

# to load transformer models
from sentence_transformers import SentenceTransformer
from transformers import T5Tokenizer, T5ForConditionalGeneration, pipeline

# To split data into train and test sets
from sklearn.model_selection import train_test_split

# To build a Random Forest model
from sklearn.ensemble import RandomForestClassifier

# To compute metrics to evaluate the model
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, precision_score, recall_score

# to ignore unnecessary warnings
import warnings
warnings.filterwarnings("ignore")

# Import TensorFlow and Keras for deep learning model building.
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

"""## **Loading the dataset**"""

# Mount Google Drive to the /content/drive directory to access the files
from google.colab import drive
drive.mount('/content/drive')

# loading data into a pandas dataframe
News = pd.read_csv("/content/drive/MyDrive/Dataset/GenAIDataset/stock_news (1).csv")

# creating a copy of the data
data = News.copy()

"""## **Data Overview**

###**Checking the first 5 rows**
"""

data.head()

"""###**Checking the last 5 rows**"""



"""###**Checking the shape of the data**"""

data.shape

"""###**Checking for missing values**"""

data.isnull().sum()

"""### **Checking for duplicate values**"""

data.duplicated().sum()

data.info()

"""## **Exploratory Data Analysis**"""

# To display the structure of data

data['Date'] = pd.to_datetime(data['Date'])

data['Date'].dtype

data.describe().T

"""### **Univariate Analysis**

* Distribution of individual variables
* Compute and check the distribution of the length of news content
* Monthwise Analysis

### **Distribution of Sentiment polarity and all Numeric Variables**
"""

plt.figure(figsize=(6, 4))
sns.countplot(data=data, x='Label')
plt.title('Distribution of Sentiment Polarity')
plt.xlabel('Sentiment Label (-1: Negative, 0: Neutral, 1: Positive)')
plt.ylabel('Count')
plt.show()

# Distribution of sentiment polarity
plt.figure(figsize=(8,5))

sns.countplot(x='Label', data=data)

plt.title('Distribution of Sentiment Polarity')
plt.xlabel('Sentiment')
plt.ylabel('Count')
plt.xticks(ticks=[0,1,2], labels=['Negative','Neutral','Positive'])

plt.tight_layout()
plt.show()

# Plot Distribution of all Numeric variables
numeric_cols = ['Open', 'High', 'Low', 'Close', 'Volume']

avg_values = data[numeric_cols].mean()

plt.figure(figsize=(10,6))

plt.bar(avg_values.index, avg_values.values, color='skyblue')

plt.title('Average of Numeric Variables')
plt.xlabel('Variables')
plt.ylabel('Average Value')

plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

numeric_cols = ['Open', 'High', 'Low', 'Close', 'Volume']

plt.figure(figsize=(15, 10))
for i, col in enumerate(numeric_cols, 1):
    plt.subplot(3, 2, i) # Arrange plots in a 3x2 grid
    if col == 'Volume':
        sns.histplot(data=data, x=col, kde=True) # Use histplot for volume as it's count data
    else:
        sns.kdeplot(data=data, x=col, fill=True) # Use kdeplot for price data
    plt.title(f'Distribution of {col}')
    plt.xlabel(col)
    plt.ylabel('Density' if col != 'Volume' else 'Count')
plt.tight_layout() # Adjust layout to prevent overlapping titles/labels
plt.show()

"""### **Distribution of the length of news content**"""

# Compute length of news content (in words)
data['News_Length'] = data['News'].apply(lambda x: len(str(x).split()))

# Summary statistics of news length
print(data['News_Length'].describe())

# Plot distribution
plt.figure(figsize=(10, 6))
sns.histplot(data=data, x='News_Length', kde=True)
plt.title('Distribution of News Content Length (Words)')
plt.xlabel('Number of Words')
plt.ylabel('Frequency')
plt.show()

"""### **Monthwise Analysis**"""

#Create a YearMonth column
data['YearMonth'] = data['Date'].dt.to_period('M').astype(str)

# Group by YearMonth and calculate averages
monthwise_avg = (
    data.groupby('YearMonth')[['High', 'Low', 'Open', 'Close','Volume']]
      .mean()
      .reset_index()
)

print(monthwise_avg)

monthwise_avg = data.groupby('YearMonth')[['Open', 'High', 'Low', 'Close']].mean()

monthwise_avg.plot(kind='bar', figsize=(12,6))

plt.title('Monthwise Average Stock Prices')
plt.xlabel('Month')
plt.ylabel('Average Price')
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.tight_layout()
plt.show()

"""* Price Trend (High, Low, Open, Close) shows that there is a steady increase in all price measures from January to April 2019."""

#plot the trend of monthwise averages in Volume
plt.figure(figsize=(12,6))

# Re-calculate monthwise_avg to ensure it includes 'Volume' and 'YearMonth' as a column
# This is necessary because the previous cell (lwt39HZfcmrh) redefined monthwise_avg
# without the 'Volume' column and with 'YearMonth' as an index.
monthwise_avg = (
    data.groupby('YearMonth')[['Open', 'High', 'Low', 'Close','Volume']]
      .mean()
      .reset_index()
)

plt.bar(monthwise_avg['YearMonth'].astype(str), monthwise_avg['Volume'])

plt.title('Monthwise Average Volume')
plt.xlabel('Month')
plt.ylabel('Average Volume')

plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.tight_layout()
plt.show()

# Bar plot of the monthwise averages in Volume
plt.figure(figsize=(10, 6))
sns.barplot(x='YearMonth', y='Volume', data=monthwise_avg, palette='viridis')
plt.title('Month-wise Average Volume (Bar Plot)')
plt.xlabel('Month')
plt.ylabel('Average Volume')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

numeric_cols = ['Open', 'High', 'Low', 'Close', 'Volume']

plt.figure(figsize=(15, 10))
for i, col in enumerate(numeric_cols, 1):
    plt.subplot(3, 2, i) # Arrange plots in a 3x2 grid
    sns.boxplot(y=data[col])
    plt.title(f'Box Plot of {col}')
    plt.ylabel(col)
plt.tight_layout()
plt.show()

"""### **Bivariate Analysis**

* Correlation
* Sentiment Polarity vs Price
* Date vs Price
* Distribution of News Length Across Sentiment Categories

### **Correlation**
"""

# Correlation matrix to check if variables move together or have correlations
plt.figure(figsize=(10, 8))
sns.heatmap(data[numeric_cols].corr(), annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Matrix of Numeric Variables')
plt.show()

"""### **Sentiment Polarity vs Price**"""

price_cols = ['Open', 'High', 'Low', 'Close']

plt.figure(figsize=(15, 10))
for i, col in enumerate(price_cols, 1):
    plt.subplot(2, 2, i) # Arrange plots in a 2x2 grid
    sns.barplot(x='Label', y=col, data=data, palette='viridis')
    plt.title(f'Average {col} Price vs Sentiment Polarity')
    plt.xlabel('Sentiment Label (-1: Negative, 0: Neutral, 1: Positive)')
    plt.ylabel(f'Average {col} Price')
plt.tight_layout()
plt.show()

"""### **Time Series Analysis (Date vs Price)**"""

# Time Series Analysis (Date vs Price columns)
plt.figure(figsize=(15, 8))
plt.plot(data['Date'], data['Open'], label='Open')
plt.plot(data['Date'], data['High'], label='High')
plt.plot(data['Date'], data['Low'], label='Low')
plt.plot(data['Date'], data['Close'], label='Close')
plt.title('Stock Prices Over Time')
plt.xlabel('Date')
plt.ylabel('Price')
plt.legend()
plt.grid(True)
plt.show()

"""### **Distribution of News Length Across Sentiment Categories**"""

# Distribution of News Length Across Sentiment Categories
plt.figure(figsize=(10, 6))
sns.boxplot(x='Label', y='News_Length', data=data, palette='coolwarm')
plt.title('Distribution of News Length Across Sentiment Categories')
plt.xlabel('Sentiment Label (-1: Negative, 0: Neutral, 1: Positive)')
plt.ylabel('News Length (Words)')
plt.show()

"""## **Data Preprocessing**

* Split the dataset into training and test sets using an **80:20** ratio with **train_test_split** (random_state=42) to ensure reproducibility.

* The feature matrix  **X** contains text embeddings generated from the embedding stage.

* The dimensionality of **X** varies depending on the embedding model used.

* For each embedding type, separate **X_train and X_test splits** were created, paired with the target **y_train, y_test**.
"""

# Storing target variable
y = data['Label']

y = data['Label']

"""## **Word Embeddings**

#### **Word2Vec**
"""

# Creating a list of all words in our data
word_tokenize = [news.split() for news in data['News']]

# Training the Word2Vec model
vec_size = 100  # Set the desired vector size
Word2Vec_model = Word2Vec(word_tokenize, vector_size=vec_size, min_count=5)



# Retrieving word vectors for all the words present in the model's vocabulary
words = Word2Vec_model.wv.index_to_key

# Creating a dictionary of words and their corresponding vectors
word_vector_dict = Word2Vec_model.wv

def average_vectorizer_Word2Vec(doc):
    # Initializing a feature vector for the sentence
    feature_vector = np.zeros((vec_size,), dtype="float64")

    # Creating a list of words in the sentence that are present in the model vocabulary
    words_in_vocab = [word for word in doc.split() if word in words]

    # adding the vector representations of the words
    for word in words_in_vocab:
        feature_vector += np.array(word_vector_dict[word])

    # Dividing by the number of words to get the average vector
    if len(words_in_vocab) != 0:
        feature_vector /= len(words_in_vocab)

    return feature_vector

# creating a dataframe of the vectorized documents
X = pd.DataFrame([average_vectorizer_Word2Vec(news) for news in data['News']])

"""## **Sentence Transformer**

####**Generating Embeddings with Sentence Tranformers using the BAAI/bge-base-en-v1.5 text embedding**
"""

model = SentenceTransformer('BAAI/bge-base-en-v1.5')

"""##### Encoding the dataset"""

embedding_matrix = model.encode(data['News'])

# printing the shape of the embedding matrix
print(embedding_matrix.shape)

"""## **Sentiment Analysis**

### **Model Evaluation Criterion**

- Plot a **confusion matrix** (`plot_confusion_matrix`)
- Generate key **classification metrics** like accuracy, recall, precision, and F1-score (`model_performance_classification_sklearn`)

##### **Utility Functions**
"""

def plot_confusion_matrix(actual, predicted):
    """
    Plot a confusion matrix to visualize the performance of a classification model.

    Parameters:
    actual (array-like): The true labels.
    predicted (array-like): The predicted labels from the model.

    Returns:
    None: Displays the confusion matrix plot.
    """

    # Compute the confusion matrix.
    cm = confusion_matrix(actual, predicted)

    # Create a new figure with a specified size
    plt.figure(figsize=(5, 4))

    # Define the labels for the confusion matrix dynamically from the data
    label_list = sorted(list(np.unique(np.concatenate((actual, predicted)))))

    # Plot the confusion matrix using a heatmap with annotations
    sns.heatmap(cm, annot=True, fmt='.0f', cmap='Blues', xticklabels=label_list, yticklabels=label_list)

    # Label for the y-axis
    plt.ylabel('Actual')

    # Label for the x-axis
    plt.xlabel('Predicted')

    # Title of the plot
    plt.title('Confusion Matrix')

    # Display the plot
    plt.show()

def model_performance_classification_sklearn(actual, predicted):
    """
    Compute various performance metrics for a classification model using sklearn.

    Parameters:
    model (sklearn classifier): The classification model to evaluate.
    predictors (array-like): The independent variables used for predictions.
    target (array-like): The true labels for the dependent variable.

    Returns:
    pandas.DataFrame: A DataFrame containing the computed metrics (Accuracy, Recall, Precision, F1-score).
    """

    # Compute Accuracy
    acc = accuracy_score(actual,predicted)
    # Compute Recall
    recall = recall_score(actual,predicted,average='weighted')
    # Compute Precision
    precision = precision_score(actual,predicted,average='weighted')
    # Compute F1-score
    f1 = f1_score(actual,predicted,average='weighted')

    # Create a DataFrame to store the computed metrics
    df_perf = pd.DataFrame(
        {
            "Accuracy": [acc],
            "Recall": [recall],
            "Precision": [precision],
            "F1": [f1],
        }
    )
    # Return the DataFrame with the metrics
    return df_perf

"""## **Build Random Forest Models using different text embeddings**

### **Word2Vec-Random Forest Model**
"""

# Storing independent variable
X = data[['Open', 'High', 'Low', 'Close', 'Volume']]

# Split data into training and testing set.
X_train, X_test, y_train, y_test = train_test_split(X ,y, test_size = 0.2, random_state = 42)

# Building the model
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)

# Fitting on train data
rf_model.fit(X_train, y_train)

# Predicting on train data
y_pred_train = rf_model.predict(X_train)

# Predicting on test data
y_pred_test = rf_model.predict(X_test)

plot_confusion_matrix(y_train, y_pred_train)

plot_confusion_matrix(y_test, y_pred_test)

train_Word2Vec_RF = model_performance_classification_sklearn(y_train,y_pred_train)
print("Training set performance metrics:")
print(train_Word2Vec_RF.to_string(index=False))
test_Word2Vec_RF = model_performance_classification_sklearn(y_test,y_pred_test)
print("Test set performance metrics:")
print(test_Word2Vec_RF.to_string(index=False))

"""###**Sentence Transformer-Random Forest Model**"""

# Storing independent variable
X = embedding_matrix

# Split data into training and testing set.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Building the model
rf_model_BAAI = RandomForestClassifier(n_estimators=100, random_state=42)

# Fitting on train data
rf_model_BAAI.fit(X_train, y_train)

# Predicting on train data
y_pred_train = rf_model_BAAI.predict(X_train)

# Predicting on test data
y_pred_test = rf_model_BAAI.predict(X_test)

plot_confusion_matrix(y_train, y_pred_train)

plot_confusion_matrix(y_test, y_pred_test)

train_transformer_BAAI_RF = model_performance_classification_sklearn(y_train,y_pred_train)
print("Training set performance metrics:")
print(train_transformer_BAAI_RF.to_string(index=False))
test_transformer_BAAI_RF = model_performance_classification_sklearn(y_test,y_pred_test)
print("Test set performance metrics:")
print(test_transformer_BAAI_RF.to_string(index=False))

"""### **Building Neural Network Models using different text embeddings**

### **Word2Vec-Neural Network Model**
"""

# Storing independent variable
X = pd.DataFrame([average_vectorizer_Word2Vec(news) for news in data['News']])

# Split data into training and testing set.
X_train, X_test, y_train, y_test = train_test_split(X ,y, test_size = 0.2, random_state = 42)

label_map = {-1: 0, 0: 1, 1: 2}
y_train_mapped = np.array([label_map[y] for y in y_train])
y_test_mapped = np.array([label_map[y] for y in y_test])

import gc

# Clear previous sessions
tf.keras.backend.clear_session()
gc.collect()

model = Sequential([
    Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
    Dropout(0.3),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(3, activation='softmax')  # 3 output neurons for 3 classes
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

history = model.fit(
    X_train, y_train_mapped,
    validation_data=(X_test, y_test_mapped),
    epochs=20,
    batch_size=32
)

# Predict class probabilities on training data
y_train_pred_probs = model.predict(X_train)
# Convert probabilities to class labels
y_train_preds = np.argmax(y_train_pred_probs, axis=1)

# Predict class probabilities on test data
y_test_pred_probs = model.predict(X_test)
# Convert probabilities to class labels
y_test_preds = np.argmax(y_test_pred_probs, axis=1)

plot_confusion_matrix(y_train_mapped, y_train_preds)

plot_confusion_matrix(y_test_mapped, y_test_preds)

train_Word2Vec_NN = model_performance_classification_sklearn(y_train_mapped, y_train_preds)
print("Training set performance metrics:")
print(train_Word2Vec_NN .to_string(index=False))
test_Word2Vec_NN  = model_performance_classification_sklearn(y_test_mapped, y_test_preds)
print("Test set performance metrics:")
print(test_Word2Vec_NN .to_string(index=False))

"""### **Generating Embeddings with Sentence Tranformers using the BAAI/bge-base-en-v1.5 embedding -Neural Network model**"""

X = embedding_matrix
# Split data into training and testing set.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

label_map = {-1: 0, 0: 1, 1: 2}
y_train_mapped = np.array([label_map[y] for y in y_train])
y_test_mapped = np.array([label_map[y] for y in y_test])

import gc

# Clear previous sessions
tf.keras.backend.clear_session()
gc.collect()

model = Sequential([
    Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
    Dropout(0.3),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(3, activation='softmax')  # 3 output neurons for 3 classes
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

history = model.fit(
    X_train, y_train_mapped,
    validation_data=(X_test, y_test_mapped),
    epochs=20,
    batch_size=32
)

# Predict class probabilities on training data
y_train_pred_probs = model.predict(X_train)
# Convert probabilities to class labels
y_train_preds = np.argmax(y_train_pred_probs, axis=1)

# Predict class probabilities on test data
y_test_pred_probs = model.predict(X_test)
# Convert probabilities to class labels
y_test_preds = np.argmax(y_test_pred_probs, axis=1)

plot_confusion_matrix(y_train_mapped, y_train_preds)

plot_confusion_matrix(y_test_mapped, y_test_preds)

train_transformer_BAAI_NN = model_performance_classification_sklearn(y_train_mapped, y_train_preds)
print("Training set performance metrics:")
print(train_transformer_BAAI_NN .to_string(index=False))
test_transformer_BAAI_NN  = model_performance_classification_sklearn(y_test_mapped, y_test_preds)
print("Test set performance metrics:")
print(test_transformer_BAAI_NN .to_string(index=False))

"""### **Generating Embeddings with Sentence Tranformers using the all-MiniLM-L6-v2 embedding**"""

# Load the Sentence Transformer model
model_MiniLM = SentenceTransformer('all-MiniLM-L6-v2')

"""##### Encoding the dataset"""

embedding_matrix_MiniLM = model_MiniLM.encode(data['News'])
print(embedding_matrix_MiniLM.shape)

"""### **Sentence Transformer-all-MiniLM-L6-v2-Random Forest Model**"""

# Storing independent variable
X = embedding_matrix_MiniLM

# Split data into training and testing set.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Building the model
rf_model_MiniLM = RandomForestClassifier(n_estimators=100, random_state=42)

# Fitting on train data
rf_model_MiniLM.fit(X_train, y_train)

# Predicting on train data
y_pred_train_MiniLM = rf_model_MiniLM.predict(X_train)

# Predicting on test data
y_pred_test_MiniLM = rf_model_MiniLM.predict(X_test)

plot_confusion_matrix(y_train, y_pred_train_MiniLM)

plot_confusion_matrix(y_test, y_pred_test_MiniLM)

train_transformer_MiniLM_RF = model_performance_classification_sklearn(y_train, y_pred_train_MiniLM)
print("Training set performance metrics:")
print(train_transformer_MiniLM_RF.to_string(index=False))
test_transformer_MiniLM_RF = model_performance_classification_sklearn(y_test, y_pred_test_MiniLM)
print("Test set performance metrics:")
print(test_transformer_MiniLM_RF.to_string(index=False))

"""### **Sentence Transformer-all-MiniLM-L6-v2-Neural Network Model**"""

# Storing independent variable
X = embedding_matrix_MiniLM

# Split data into training and testing set.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

label_map = {-1: 0, 0: 1, 1: 2} # Re-define for clarity if needed, or ensure it's in scope
y_train_mapped = np.array([label_map[y] for y in y_train])
y_test_mapped = np.array([label_map[y] for y in y_test])

import gc

# Clear previous sessions
tf.keras.backend.clear_session()
gc.collect()

model_MiniLM_NN = Sequential([
    Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
    Dropout(0.3),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(3, activation='softmax')  # 3 output neurons for 3 classes
])

model_MiniLM_NN.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model_MiniLM_NN.summary()

history_MiniLM_NN = model_MiniLM_NN.fit(
    X_train, y_train_mapped,
    validation_data=(X_test, y_test_mapped),
    epochs=20,
    batch_size=32
)

# Predict class probabilities on training data
y_train_pred_probs_MiniLM_NN = model_MiniLM_NN.predict(X_train)
# Convert probabilities to class labels
y_train_preds_MiniLM_NN = np.argmax(y_train_pred_probs_MiniLM_NN, axis=1)

# Predict class probabilities on test data
y_test_pred_probs_MiniLM_NN = model_MiniLM_NN.predict(X_test)
# Convert probabilities to class labels
y_test_preds_MiniLM_NN = np.argmax(y_test_pred_probs_MiniLM_NN, axis=1)

plot_confusion_matrix(y_train_mapped, y_train_preds_MiniLM_NN)

plot_confusion_matrix(y_test_mapped, y_test_preds_MiniLM_NN)

train_transformer_MiniLM_NN = model_performance_classification_sklearn(y_train_mapped, y_train_preds_MiniLM_NN)
print("Training set performance metrics:")
print(train_transformer_MiniLM_NN.to_string(index=False))
test_transformer_MiniLM_NN = model_performance_classification_sklearn(y_test_mapped, y_test_preds_MiniLM_NN)
print("Test set performance metrics:")
print(test_transformer_MiniLM_NN.to_string(index=False))

"""### **Hyperparameter Tuning for Sentence Transformer-all-MiniLM-L6-v2 Neural Network Model**"""

# Install scikeras to enable Keras models to be used with scikit-learn's API
!pip install scikeras

import tensorflow as tf
import numpy as np
from sklearn.model_selection import train_test_split
from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import uniform, randint
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

# Ensure X and y are set up for the MiniLM Neural Network model
X = embedding_matrix_MiniLM
# y is already defined globally as data['Label']

# Split data into training and testing set (re-running for clarity, ensures correct split)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Map target labels from -1, 0, 1 to 0, 1, 2 for sparse_categorical_crossentropy
label_map = {-1: 0, 0: 1, 1: 2}
y_train_mapped = np.array([label_map[val] for val in y_train])
y_test_mapped = np.array([label_map[val] for val in y_test])

# Function to create Keras model for RandomizedSearchCV (returns an uncompiled model)
def create_nn_model(neurons1=128, dropout1=0.3, neurons2=64, dropout2=0.3):
    tf.keras.backend.clear_session()
    model = Sequential([
        Dense(neurons1, activation='relu', input_shape=(X_train.shape[1],)),
        Dropout(dropout1),
        Dense(neurons2, activation='relu'),
        Dropout(dropout2),
        Dense(3, activation='softmax')
    ])
    # KerasClassifier will compile the model, so do not compile it here.
    return model

# Create a KerasClassifier wrapper
# Specify optimizer, loss, and metrics here for KerasClassifier to handle compilation
keras_model = KerasClassifier(
    model=create_nn_model,
    optimizer='adam',  # Specify optimizer as a string or class
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy'],
    epochs=20,
    batch_size=32,
    verbose=0
)

# Define parameter distributions for RandomizedSearchCV
param_dist = {
    'model__neurons1': randint(64, 256),
    'model__dropout1': uniform(0.1, 0.5),
    'model__neurons2': randint(32, 128),
    'model__dropout2': uniform(0.1, 0.5),
    'optimizer__learning_rate': uniform(loc=0.0001, scale=0.01), # Correct prefix for optimizer parameters
    'batch_size': [16, 32, 64],
    'epochs': [20, 30, 40]
}

# Initialize RandomizedSearchCV
# n_iter: Number of parameter settings that are sampled. Reduce if it takes too long.
# cv: Number of folds for cross-validation. Reduce if it takes too long.
random_search = RandomizedSearchCV(estimator=keras_model, param_distributions=param_dist,
                                   n_iter=10, cv=3, verbose=1, random_state=42, n_jobs=-1)

# Fit RandomizedSearchCV
print("Starting RandomizedSearchCV...")
random_search_result = random_search.fit(X_train, y_train_mapped)
print("RandomizedSearchCV finished.")

# Print best parameters and best score
print("Best Score: %f using %s" % (random_search_result.best_score_, random_search_result.best_params_))

# Get the best model
best_nn_model = random_search_result.best_estimator_

"""#### **Evaluate the Best Hyperparameter Tuned MiniLM Neural Network Model**"""

# Predict on training data with the best model
y_train_pred_probs_best_nn = best_nn_model.predict_proba(X_train)
y_train_preds_best_nn = np.argmax(y_train_pred_probs_best_nn, axis=1)

# Predict on test data with the best model
y_test_pred_probs_best_nn = best_nn_model.predict_proba(X_test)
y_test_preds_best_nn = np.argmax(y_test_pred_probs_best_nn, axis=1)

# Plot confusion matrix for training set
plot_confusion_matrix(y_train_mapped, y_train_preds_best_nn)

# Plot confusion matrix for test set
plot_confusion_matrix(y_test_mapped, y_test_preds_best_nn)

# Get performance metrics for training set
train_transformer_MiniLM_NN_tuned = model_performance_classification_sklearn(y_train_mapped, y_train_preds_best_nn)
print("Training set performance metrics for tuned model:")
print(train_transformer_MiniLM_NN_tuned.to_string(index=False))

# Get performance metrics for test set
test_transformer_MiniLM_NN_tuned = model_performance_classification_sklearn(y_test_mapped, y_test_preds_best_nn)
print("Test set performance metrics for tuned model:")
print(test_transformer_MiniLM_NN_tuned.to_string(index=False))

"""The tuning process will help us find better hyperparameters for the Neural Network. After this, we can re-evaluate the model. If we still don't reach 90%, we can discuss further steps such as exploring more advanced models or data augmentation techniques.

The last two comparison cells (`w1-DljKZTsyH` and `q9LcgdCciUX5`) can now be re-executed to display the full performance summary.

The accuracy of the best performing model is: 0.5571

Based on the evaluation of all trained models, the **Sentence Transformer-all-MiniLM-L6-v2 (Neural Network)** model demonstrated the highest accuracy on the test set. This indicates that this model performs best on unseen data compared to the other models evaluated, including the hyperparameter-tuned one which had slightly lower test accuracy.

### **Model Comparison and Selection**
"""

models_test_comp_df = pd.DataFrame({
    'Word2Vec (Random Forest)': test_Word2Vec_RF.iloc[0],
    'Sentence Transformer-BAAI/bge-base-en-v1.5 (Random Forest)': test_transformer_BAAI_RF.iloc[0],
    'Word2Vec (Neural Network)': test_Word2Vec_NN.iloc[0],
    'Sentence Transformer-BAAI/bge-base-en-v1.5 (Neural Network)': test_transformer_BAAI_NN.iloc[0],
    'Sentence Transformer-all-MiniLM-L6-v2 (Random Forest)': test_transformer_MiniLM_RF.iloc[0],
    'Sentence Transformer-all-MiniLM-L6-v2 (Neural Network)': test_transformer_MiniLM_NN.iloc[0],
    'Sentence Transformer-all-MiniLM-L6-v2 (Tuned Neural Network)': test_transformer_MiniLM_NN_tuned.iloc[0]
}).T

# Sort by F1 score to easily identify the best model
models_test_comp_df = models_test_comp_df.sort_values(by='F1', ascending=False)

print("Test performance comparison:")
display(models_test_comp_df)

best_model_name = models_test_comp_df.index[0]
best_f1_score = models_test_comp_df.iloc[0]['F1']

print(f"\nBased on the F1-score, the best performing model on the test set is the '{best_model_name}' with an F1 score of {best_f1_score:.4f}.")

"""Based on the F1-score, the best performing model on the test set is the 'Sentence Transformer-all-MiniLM-L6-v2 (Neural Network)' with an F1 score of 0.6230.

# Conclusion

In this analysis, we explored various combinations of text embedding techniques and classification models to perform sentiment analysis on stock news data. We evaluated models built using:

*   **Word2Vec embeddings** paired with **Random Forest** and **Neural Networks**.
*   **Sentence Transformer embeddings** (specifically `BAAI/bge-base-en-v1.5` and `all-MiniLM-L6-v2`) paired with both **Random Forest** and **Neural Networks**.

Our comprehensive evaluation, with a focus on the F1-score due to potential class imbalance, revealed that the **'Sentence Transformer-all-MiniLM-L6-v2 (Neural Network)'** model achieved the highest F1-score of **0.6230** on the test set. This indicates that this particular combination of a sophisticated pre-trained sentence embedding model and a Neural Network architecture is most effective in capturing the sentiment polarity from news content.

While other models like the `Sentence Transformer-BAAI/bge-base-en-v1.5 (Neural Network)` also showed promising results, the `all-MiniLM-L6-v2` model provided a slightly better balance of precision and recall. Hyperparameter tuning on the best performing Neural Network model (`Sentence Transformer-all-MiniLM-L6-v2 (Neural Network)`) resulted in a slightly lower F1-score of 0.5260 on the test set, suggesting that the initial parameters already provided a robust performance, or further tuning with more extensive search spaces might be beneficial.

Overall, the superior performance of models utilizing Sentence Transformers, especially when combined with Neural Networks, underscores the effectiveness of dense, contextualized embeddings for this sentiment analysis task.

## **Conclusions and Recommendations**

Based on the comprehensive evaluation, the **'Sentence Transformer-all-MiniLM-L6-v2 (Neural Network)'** model is recommended as the most effective solution for sentiment analysis on stock news data, achieving the highest F1-score of **0.6230** on the test set. This model leverages the power of contextualized embeddings combined with a neural network's ability to learn complex patterns, proving superior to traditional Word2Vec embeddings and simpler Random Forest classifiers.

### Key Recommendations:

1.  **Adopt the 'Sentence Transformer-all-MiniLM-L6-v2 (Neural Network)' model**: This model has demonstrated the best performance in classifying sentiment polarity from news articles, making it a reliable choice for gauging market sentiment.

2.  **Integrate Sentiment Scores for Stock Price Prediction**: The sentiment scores generated by this model can be integrated as a crucial feature in the investment startup's stock price prediction models. This will provide valuable insights into market sentiment, which is a significant driver of stock price fluctuations.

3.  **Develop a Weekly News Summarization Module**: As outlined in the problem definition, an essential next step is to build a system for summarizing news at a weekly level. This would involve:
    *   **Aggregating Sentiment**: Calculating a composite weekly sentiment score (e.g., average, weighted average, or majority class) from the daily sentiment predictions.
    *   **Key Phrase/Sentence Extraction**: Utilizing techniques like TF-IDF, TextRank, or more advanced summarization models (e.g., BART, T5) to extract the most salient information from the news articles for each week, reflecting the overall sentiment.

4.  **Continuous Monitoring and Retraining**: Financial news and market sentiment are dynamic. It is crucial to establish a pipeline for:
    *   **Monitoring Model Performance**: Regularly evaluate the model's accuracy and F1-score against new, unseen data.
    *   **Data Drift Detection**: Implement mechanisms to detect shifts in news language or sentiment patterns that might degrade model performance over time.
    *   **Periodic Retraining**: Retrain the model with updated news data to ensure its continued relevance and accuracy in an evolving market.

5.  **Explore Advanced Deep Learning Architectures**: While the current Neural Network performs well, further improvements could be explored with more sophisticated architectures (e.g., LSTMs, GRUs, or attention-based models) especially if the sequential nature of news over time becomes a critical factor in sentiment analysis.

By implementing these recommendations, the investment startup can enhance its AI-driven sentiment analysis system, providing financial analysts with more actionable insights and ultimately improving investment decision-making and client outcomes.

#End
"""